#!/bin/bash

# Function to ensure sudo
ensure_sudo() {
    if ! sudo -n true 2>/dev/null; then
        echo "Please enter your password to continue:"
        sudo -v
        # Keep sudo alive
        while true; do
            sudo -n true
            sleep 60
            kill -0 "$$" 2>/dev/null || exit
        done 2>/dev/null &
    fi
}

ensure_sudo

gpg --quiet --decrypt /etc/vpn/pass.gpg | sudo openconnect \
    --protocol=fortinet \
    --user=user@mail.com \
    --servercert yourcert ]
    --passwd-on-stdin \
    vpn.example.com
